import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-zinc-200 text-zinc-900 flex-col min-h-screen`}
      >
        <ClerkProvider>
          <div className="flex flex-col justify-between gap-7 min-h-screen">
            <Header />
            {children}
            <Footer />
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
